#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

 $curpath = realpath(dirname(__FILE__));
 if (!file_exists($curpath.'/yiic.php')) {
   $curpath = realpath($curpath.'/../tashik/yii2-migrate/');
 }
 require_once(dirname(__FILE__).'/yiic.php');